import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-w-full">
          <h1 className="bg-slate-900 text-2xl flex justify-center">
            RootLayout
          </h1>
        </div>
        {children}
      </body>
    </html>
  );
}
