import Navigation from './components/Navigation'
import './globals.css'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const navLinks = [
    {
      name: 'Home',
      href: '/'
    },
    {
      name: 'Dashboard',
      href: '/dashboard'
    },
    {
      name: 'Blog',
      href: '/blog'
    }
  ]
  return (
    <html lang="en">
      <body>
        <Navigation navLinks={navLinks}/>
        {children}
        </body>
    </html>
  )
}
